/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.autor;

import app.Lista;
import app.modelos.AutorModelo;
import java.util.Calendar;
import mojica.alexander.utilidades.Mensaje;
import mojica.alexander.utilidades.Validacion;

/**
 *
 * @author MekakuZero
 */
public class FrameModificarAutor extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    AutorModelo autor;
    Lista lista;
    
    public FrameModificarAutor(AutorModelo autor, Lista lista) {
        initComponents();
        this.autor = autor;
        this.lista = lista;
        limpiar();
    }

    public void limpiar(){
        this.txtNombre.setText(autor.getNombre());
        this.txtApellido.setText(autor.getApellido());
        this.txtSeudonimo.setText(autor.getSeudonimo());
        this.dccFechaNacimiento.setSelectedDate(Validacion.toCalendar(autor.getFecha_nacimiento()));
        
        this.lblErrorFechaNacimiento.setText("");
        this.lblErrorSeudonimo.setText("");
        this.lblErrorNombre.setText("");
        this.lblErrorApellido.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottom = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlFila1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorApellido = new javax.swing.JLabel();
        pnlFila2 = new javax.swing.JPanel();
        lblErrorSeudonimo = new javax.swing.JLabel();
        lblSeudonimo = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblErrorFechaNacimiento = new javax.swing.JLabel();
        txtSeudonimo = new javax.swing.JTextField();
        dccFechaNacimiento = new datechooser.beans.DateChooserCombo();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar usuario");
        setToolTipText("");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 4));

        pnlBottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        pnlBottom.setPreferredSize(new java.awt.Dimension(405, 75));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        getContentPane().add(pnlBottom, java.awt.BorderLayout.PAGE_END);

        pnlCenter.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion del usuario"));
        pnlCenter.setLayout(new java.awt.GridLayout(2, 0));

        pnlFila1.setPreferredSize(new java.awt.Dimension(393, 100));

        lblNombre.setText("Nombre:");

        lblApellido.setText("Apellido:");

        lblErrorNombre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNombre.setText("error");

        lblErrorApellido.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorApellido.setText("error");

        javax.swing.GroupLayout pnlFila1Layout = new javax.swing.GroupLayout(pnlFila1);
        pnlFila1.setLayout(pnlFila1Layout);
        pnlFila1Layout.setHorizontalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorApellido)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlFila1Layout.setVerticalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorNombre)
                    .addComponent(lblErrorApellido))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlFila1);

        lblErrorSeudonimo.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSeudonimo.setText("error");

        lblSeudonimo.setText("Seudonimo:");

        lblFechaNacimiento.setText("Fecha de nacimiento:");

        lblErrorFechaNacimiento.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorFechaNacimiento.setText("error");

        javax.swing.GroupLayout pnlFila2Layout = new javax.swing.GroupLayout(pnlFila2);
        pnlFila2.setLayout(pnlFila2Layout);
        pnlFila2Layout.setHorizontalGroup(
            pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeudonimo)
                    .addComponent(txtSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorSeudonimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dccFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(pnlFila2Layout.createSequentialGroup()
                        .addGroup(pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaNacimiento)
                            .addComponent(lblErrorFechaNacimiento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFila2Layout.setVerticalGroup(
            pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFila2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeudonimo)
                    .addComponent(lblFechaNacimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFila2Layout.createSequentialGroup()
                        .addComponent(txtSeudonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorSeudonimo))
                    .addGroup(pnlFila2Layout.createSequentialGroup()
                        .addComponent(dccFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorFechaNacimiento)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlCenter.add(pnlFila2);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        // Obtenemos los getModelo del autor
        String nombre = this.txtNombre.getText().trim();
        String apellido = this.txtApellido.getText().trim();
        String seudonimos = this.txtSeudonimo.getText().trim();
        java.util.Date fecha = null;

        try{
            fecha = this.dccFechaNacimiento.getSelectedDate().getTime();
        } catch(Exception error){}

        // Realixamos la comprobaciones
        if (Validacion.valaidadTexto(this.lblErrorSeudonimo, seudonimos) 
                & Validacion.noNulo(this.lblErrorFechaNacimiento, fecha)
                & Validacion.valaidadTextoNuleable(this.lblErrorNombre, nombre, Validacion.NOMBRES)
                & Validacion.valaidadTextoNuleable(this.lblErrorApellido, apellido, Validacion.NOMBRES)
                ) {
            AutorModelo autor = new AutorModelo(this.autor);

            autor.setFecha_nacimiento(fecha);
            autor.setSeudonimo(seudonimos);
            autor.setNombre((nombre.isEmpty())? null : nombre);
            autor.setApellido((apellido.isEmpty())? null : apellido);

            if (autor.actualizar()) {
                Mensaje.Informacion("El autor ha sido almacenado con exito", title);
                this.lista.actualizarLista();
                this.dispose();
            } else
                Mensaje.Error("No se ha podido almacenar el autor", title);
        } else
        Mensaje.Error("Informacion incorrecta", title);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (autor.eliminar()) {
            Mensaje.Informacion("El autor ha sido eliminado", title);
            this.lista.actualizarLista();
            this.dispose();
        } else
            Mensaje.Error("No se ha podido eliminar el autor", title);
    }//GEN-LAST:event_btnEliminarActionPerformed

    @Override
    public void dispose() {
        FrameAutorLista.frameModificar = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private datechooser.beans.DateChooserCombo dccFechaNacimiento;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblErrorApellido;
    private javax.swing.JLabel lblErrorFechaNacimiento;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorSeudonimo;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSeudonimo;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlFila1;
    private javax.swing.JPanel pnlFila2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSeudonimo;
    // End of variables declaration//GEN-END:variables
}
