/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.temas;

import app.categoria.*;
import app.Lista;
import app.modelos.TemaModelo;
import mojica.alexander.utilidades.Mensaje;
import mojica.alexander.utilidades.Validacion;

/**
 *
 * @author MekakuZero
 */
public class FrameModificarTema extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameNuevaCategoria
     */
    TemaModelo tema; 
    Lista lista;
    
    public FrameModificarTema(TemaModelo categoria, Lista lista) {
        initComponents();
        this.tema = categoria;
        this.lista = lista;
        limpiar();
    }

    public void limpiar(){
        this.txtTema.setText(this.tema.getTema());
        this.txtDescripcion.setText(this.tema.getDescripcion());
        
        this.lblErrorTema.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblFila2 = new javax.swing.JPanel();
        lblTema = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        lblErrorTema = new javax.swing.JLabel();
        pnlFila1 = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlPie = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Modificar categoria");
        setToolTipText("");

        pnlCentro.setLayout(new java.awt.GridLayout(2, 1));

        lblTema.setText("Tema:");

        lblErrorTema.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTema.setText("error");

        javax.swing.GroupLayout lblFila2Layout = new javax.swing.GroupLayout(lblFila2);
        lblFila2.setLayout(lblFila2Layout);
        lblFila2Layout.setHorizontalGroup(
            lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblFila2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblTema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorTema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        lblFila2Layout.setVerticalGroup(
            lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblFila2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorTema)
                .addContainerGap())
        );

        pnlCentro.add(lblFila2);

        lblDescripcion.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout pnlFila1Layout = new javax.swing.GroupLayout(pnlFila1);
        pnlFila1.setLayout(pnlFila1Layout);
        pnlFila1Layout.setHorizontalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFila1Layout.setVerticalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCentro.add(pnlFila1);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlPie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones"));
        pnlPie.setPreferredSize(new java.awt.Dimension(424, 75));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPie, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String tema = this.txtTema.getText().trim();
        String descripcion = this.txtDescripcion.getText().trim();
        
        if (Validacion.valaidadTexto(this.lblErrorTema, tema, Validacion.NONUMERO)) {
            TemaModelo tem = new TemaModelo(this.tema);
            
            tem.setTema(tema);
            
            tem.setDescripcion(descripcion);
            
            if (tem.actualizar()) {
                Mensaje.Informacion("El tema ha sido actualizada con exito!", title);
                this.lista.actualizarLista();
                this.dispose();
            } else 
                Mensaje.Error("No se ha podido actualizar el tema", title);
        } else
            Mensaje.Error("Error en los campos de categoria", title);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (this.tema.eliminar()) {
            Mensaje.Informacion("El tema ha sido eliminada con exito!", title);
            this.lista.actualizarLista();
            this.dispose();
        } else
            Mensaje.Error("El tema no se ha podido eliminar", title);
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblErrorTema;
    private javax.swing.JPanel lblFila2;
    private javax.swing.JLabel lblTema;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlFila1;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables
}
