/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import app.autor.FrameAutorLista;
import app.autor.FrameNuevoAutor;
import app.categoria.FrameListaCategoria;
import app.categoria.FrameNuevaCategoria;
import app.temas.FrameListaTemas;
import app.temas.FrameNuevoTema;
import javax.swing.JComponent;
import javax.swing.JFrame;

/**
 *
 * @author MekakuZero
 */
public class Libreria extends javax.swing.JFrame implements Contenido {

    public static FrameNuevoAutor nuevoAutor = null;
    public static FrameAutorLista listaAutores = null;
    
    public static FrameNuevaCategoria nuevaCategoria = null;
    public static FrameListaCategoria listaCategorias = null;
    
    public static FrameNuevoTema nuevoTema = null;
    public static FrameListaTemas listaTemas = null;
    /**
     * Creates new form libreria
     */
    public Libreria() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        autorMenu = new javax.swing.JMenu();
        nuevoAutorMenuItem = new javax.swing.JMenuItem();
        verAutoresMenuItem = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenu();
        nuvaCategoriaMenuItem = new javax.swing.JMenuItem();
        verCategoriasMenuItem = new javax.swing.JMenuItem();
        menuTema = new javax.swing.JMenu();
        nuevoTemaMenuItem = new javax.swing.JMenuItem();
        verTemasMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema gestion de biblioteca");

        autorMenu.setText("Autores");

        nuevoAutorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        nuevoAutorMenuItem.setText("Añadir autor");
        nuevoAutorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAutorMenuItemActionPerformed(evt);
            }
        });
        autorMenu.add(nuevoAutorMenuItem);

        verAutoresMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        verAutoresMenuItem.setText("Ver autores");
        verAutoresMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAutoresMenuItemActionPerformed(evt);
            }
        });
        autorMenu.add(verAutoresMenuItem);

        menuBar.add(autorMenu);

        menuCategoria.setText("Categoria");

        nuvaCategoriaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        nuvaCategoriaMenuItem.setText("Nueva categoria");
        nuvaCategoriaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuvaCategoriaMenuItemActionPerformed(evt);
            }
        });
        menuCategoria.add(nuvaCategoriaMenuItem);

        verCategoriasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        verCategoriasMenuItem.setText("Ver categorias");
        verCategoriasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCategoriasMenuItemActionPerformed(evt);
            }
        });
        menuCategoria.add(verCategoriasMenuItem);

        menuBar.add(menuCategoria);

        menuTema.setText("Tema");

        nuevoTemaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        nuevoTemaMenuItem.setText("Nuevo tema");
        nuevoTemaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTemaMenuItemActionPerformed(evt);
            }
        });
        menuTema.add(nuevoTemaMenuItem);

        verTemasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        verTemasMenuItem.setText("Ver temas");
        verTemasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTemasMenuItemActionPerformed(evt);
            }
        });
        menuTema.add(verTemasMenuItem);

        menuBar.add(menuTema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoAutorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAutorMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevoAutor != null) nuevoAutor.dispose();
        nuevoAutor = new FrameNuevoAutor();
        this.agregarComponente(nuevoAutor);
    }//GEN-LAST:event_nuevoAutorMenuItemActionPerformed

    private void verAutoresMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAutoresMenuItemActionPerformed
        // TODO add your handling code here:
        if (listaAutores != null) listaAutores.dispose();
        listaAutores = new FrameAutorLista(this);
        this.agregarComponente(listaAutores);
    }//GEN-LAST:event_verAutoresMenuItemActionPerformed

    private void nuvaCategoriaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuvaCategoriaMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevaCategoria != null) nuevaCategoria.dispose();
        nuevaCategoria = new FrameNuevaCategoria();
        this.agregarComponente(nuevaCategoria);
    }//GEN-LAST:event_nuvaCategoriaMenuItemActionPerformed

    private void verCategoriasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCategoriasMenuItemActionPerformed
        // TODO add your handling code here:
        if (listaCategorias != null) listaCategorias.dispose();
        listaCategorias = new FrameListaCategoria(this);
        this.agregarComponente(listaCategorias);
    }//GEN-LAST:event_verCategoriasMenuItemActionPerformed

    private void nuevoTemaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTemaMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevoTema != null) nuevoTema.dispose();
        nuevoTema = new FrameNuevoTema();
        this.agregarComponente(nuevoTema);
    }//GEN-LAST:event_nuevoTemaMenuItemActionPerformed

    private void verTemasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTemasMenuItemActionPerformed
        // TODO add your handling code here:
        if (listaTemas != null) listaTemas.dispose();
        listaTemas = new FrameListaTemas(this);
        this.agregarComponente(listaTemas);
    }//GEN-LAST:event_verTemasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu autorMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuTema;
    private javax.swing.JMenuItem nuevoAutorMenuItem;
    private javax.swing.JMenuItem nuevoTemaMenuItem;
    private javax.swing.JMenuItem nuvaCategoriaMenuItem;
    private javax.swing.JMenuItem verAutoresMenuItem;
    private javax.swing.JMenuItem verCategoriasMenuItem;
    private javax.swing.JMenuItem verTemasMenuItem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void agregarComponente(JComponent comp) {
        this.desktopPane.add(comp);
        comp.show();
    }

}
