/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.categoria;

import app.Libreria;
import app.modelos.CategoriaModelo;
import mojica.alexander.utilidades.Mensaje;
import mojica.alexander.utilidades.Validacion;

/**
 *
 * @author MekakuZero
 */
public class FrameNuevaCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameNuevaCategoria
     */
    public FrameNuevaCategoria() {
        initComponents();
        limpiar();
    }

    public void limpiar(){
        this.txtCategoria.setText("");
        this.txtDescripcion.setText("");
        
        this.lblErrorCategoria.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        lblFila2 = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblErrorCategoria = new javax.swing.JLabel();
        pnlFila1 = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        pnlPie = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nueva categoria");
        setToolTipText("");

        pnlCentro.setLayout(new java.awt.GridLayout(2, 1));

        lblCategoria.setText("Categoria:");

        lblErrorCategoria.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCategoria.setText("error");

        javax.swing.GroupLayout lblFila2Layout = new javax.swing.GroupLayout(lblFila2);
        lblFila2.setLayout(lblFila2Layout);
        lblFila2Layout.setHorizontalGroup(
            lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblFila2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblFila2Layout.setVerticalGroup(
            lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblFila2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(lblFila2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorCategoria)
                .addContainerGap())
        );

        pnlCentro.add(lblFila2);

        lblDescripcion.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout pnlFila1Layout = new javax.swing.GroupLayout(pnlFila1);
        pnlFila1.setLayout(pnlFila1Layout);
        pnlFila1Layout.setHorizontalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFila1Layout.setVerticalGroup(
            pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFila1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFila1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCentro.add(pnlFila1);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlPie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones"));
        pnlPie.setPreferredSize(new java.awt.Dimension(424, 75));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPie, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String categoria = this.txtCategoria.getText().trim();
        String descripcion = this.txtDescripcion.getText().trim();
        
        if (Validacion.valaidadTexto(this.lblErrorCategoria, categoria, Validacion.NONUMERO)) {
            CategoriaModelo cat = new CategoriaModelo(categoria);
            
            if (!descripcion.isEmpty()) cat.setDescripcion(descripcion);
            
            if (cat.guardar()) {
                Mensaje.Informacion("La categoria ha sido almacenda con exito!", title);
                
                if (Libreria.listaCategorias != null) Libreria.listaCategorias.actualizarLista();
                
                limpiar();
            } else 
                Mensaje.Error("No se ha podido almacenar la catgoria", title);
        } else
            Mensaje.Error("Error en los campos de categoria", title);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblErrorCategoria;
    private javax.swing.JPanel lblFila2;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlFila1;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
